- name: Create a VIP, pool and pool members
  hosts: localhost
  connection: local
  vars:
    vcenter_hostname: VCENTER_HOSTNAME
    vcenter_username: VCENTER_USERNAME
    vcenter_password: VCENTER_PASSWORD
    name: NAME
    ip: IP
    netmask: NETMASK
    gateway: GATEWAY
  tasks:
  - name: Create a virtual machine from a template
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      folder: /
      cluster: LAB-Cluster
      name: "{{ name }}"
      state: poweredon
      datacenter: LAB-Datacenter
      template: centos-template
      networks:
      - name: Lab-Servers
        ip: "{{ ip }}"
        netmask: "{{ netmask }}"
        gateway: "{{ gateway }}"
        domain: lab.prodinfo.gca
        dns_servers:
        - 10.245.1.2
        - 10.245.2.2
        - 10.245.1.3
      wait_for_ip_address: yes
    delegate_to: localhost
    register: deploy
